
REM "C:\Program Files (x86)\Cisco\Cisco AnyConnect Secure Mobility Client\VPNCLI.EXE" connect vpn.dimensions-healthcare.com user fsheikh pwd fsheikh.FF
"C:\Program Files (x86)\Cisco Systems\VPN Client\VPNCLIENT.EXE" Disconnect 

REM psexec \\10.156.62.25 time "NET STart mssqlserver" -u "10.156.62.25\administrator" -p "=9-9#%;5+.31B5"z1yf/;;M@y"
REM psexec -u "10.156.62.25\administrator" -p "=9-9#%;5+.31B5"z1yf/;;M@y" \\10.156.62.25 time "NET STart mssqlserver"