REM taskkill /F /IM vpnui.exe
REM taskkill /F /IM vpngui.exe
REM "C:\Program Files (x86)\Cisco\Cisco AnyConnect Secure Mobility Client\VPNCLI.EXE" connect vpn.dimensions-healthcare.com user fsheikh pwd fsheikh.FF
REM "C:\Program Files (x86)\Cisco Systems\VPN Client\VPNCLIENT.EXE" Connect eHDF

REM psexec \\10.156.62.25 time "NET STart mssqlserver" -u "10.156.62.25\administrator" -p "=9-9#%;5+.31B5"z1yf/;;M@y"
d:
cd "Fazeel Data/DHC/My Projects/PSTools"
Psservice.exe \\10.4.52.32 -u 10.4.52.32\administrator -p "ux(6j@^smpM^64c.}2v,QY" restart spooler

