// <auto-generated />
namespace FS_WS_WSCTFW.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WSResponseStructureDefined : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WSResponseStructureDefined));
        
        string IMigrationMetadata.Id
        {
            get { return "201511301536192_WSResponseStructureDefined"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
